import * as SolidIcon from '@fortawesome/free-solid-svg-icons';
import * as BrandIcon from '@fortawesome/free-brands-svg-icons';

const icons = {
  ads: SolidIcon.faAd,
  amazon: BrandIcon.faAmazon,
  apple: BrandIcon.faApple,
  analytics: SolidIcon.faChartLine,
  aws: BrandIcon.faAws,
  booking: SolidIcon.faHotel,
  bitcoin: BrandIcon.faBitcoin,
  broker: SolidIcon.faHandshake,
  code: SolidIcon.faLaptopCode,
  codepen: BrandIcon.faCodepen,
  coffee: SolidIcon.faCoffee,
  coins: SolidIcon.faCoins,
  chrome: BrandIcon.faChrome,
  chromewebstoredeveloper: SolidIcon.faLaptopCode,
  credit: SolidIcon.faFileInvoiceDollar,
  derivatives: SolidIcon.faFileContract,
  dev: BrandIcon.faDev,
  digitalocean: BrandIcon.faDigitalOcean,
  dropbox: BrandIcon.faDropbox,
  ebay: BrandIcon.faEbay,
  email: SolidIcon.faEnvelope,
  facebook: BrandIcon.faFacebook,
  fire: SolidIcon.faFire,
  finance: SolidIcon.faChartBar,
  flickr: BrandIcon.faFlickr,
  github: BrandIcon.faGithub,
  googledrive: BrandIcon.faGoogleDrive,
  gov: SolidIcon.faArchway,
  news: SolidIcon.faNewspaper,
  hackernews: BrandIcon.faHackerNews,
  icloud: BrandIcon.faApple,
  indiehackers: SolidIcon.faHandHoldingUsd,
  instagram: BrandIcon.faInstagram,
  linkedin: BrandIcon.faLinkedin,
  medium: BrandIcon.faMedium,
  meetup: BrandIcon.faMeetup,
  network: SolidIcon.faNetworkWired,
  pinterest: BrandIcon.faPinterest,
  producthunt: BrandIcon.faProductHunt,
  quora: BrandIcon.faQuora,
  reddit: BrandIcon.faReddit,
  server: SolidIcon.faServer,
  soundcloud: BrandIcon.faSoundcloud,
  stripe: BrandIcon.faStripe,
  study: SolidIcon.faGraduationCap,
  telegram: BrandIcon.faTelegram,
  timebomb: SolidIcon.faBomb,
  tripadvisor: BrandIcon.faTripadvisor,
  tumblr: BrandIcon.faTumblr,
  twitter: BrandIcon.faTwitter,
  vpn: SolidIcon.faUserShield,
  wordpress: BrandIcon.faWordpress,
  yandex: BrandIcon.faYandex,
  yahoo: BrandIcon.faYahoo,
  youtube: BrandIcon.faYoutube
};

export const getIcon = name => icons[name] || SolidIcon.faLink;

export const smallIconSize = '2x';

export const largeIconSize = '3x';
