version: '3'

services:
  browser-ext:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: browser-ext
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    command: npm run start
    stdin_open: true
