name: Build and Test

on: [push]

jobs:
  collect_commit_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Collect commit message
        run: |
          echo "COMMIT_MSG=$(git show -s --format=%s)" >> "$GITHUB_ENV"
      - name: Check commit message
        run: |
          echo "Commit message was:[${COMMIT_MSG}]"

  build_and_test:
    needs: collect_commit_message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Build node app
        run: npm run build
      - name: Test node app
        run: npm test
      - name: Use commit message
        run: |
          echo "Node will use commit message:[${COMMIT_MSG}]"

# build wit node 18 (alpine)
# node:18.2.0-alpine