name: Build and Test

on: [push]

jobs:
  collect_commit_message:
    runs-on: ubuntu-latest
    outputs:
      commit_msg: ${{ steps.get-commit-msg.outputs.COMMIT_MSG }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - id: get-commit-msg
        name: Collect commit message
        run: |
          echo "COMMIT_MSG=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"
      - name: Check commit message
        env:
          commit_msg: ${{steps.get-commit-msg.outputs.commit_msg}}
        run: |
          echo "Commit message was:[${commit_msg}]"

  build_and_test:
    needs: collect_commit_message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Build node app
        run: npm run build
      - name: Test node app
        run: npm test
      - name: Use commit message
        env:
          commit_msg: ${{needs.collect_commit_message.outputs.commit_msg}}
        run: |
          echo "Node will use commit message:[${commit_msg}]"

  should_release:
    needs: [collect_commit_message, build_and_test]
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.get-release-version.outputs.RELEASE_VERSION }}
    steps:
      - name: Use commit message
        env:
          commit_msg: ${{needs.collect_commit_message.outputs.commit_msg}}
        run: |
          echo "Release check will use commit message:[${commit_msg}]"
      - name: Show release version
        env:
          commit_msg: ${{needs.collect_commit_message.outputs.commit_msg}}
        run: |
          echo ${commit_msg} | awk '{for(i=1;i<=NF;i++) if(tolower($i) ~ /release:[0-9]+\.[0-9]+\.[0-9]+/) print tolower($i)}'
      - name: Obtain release version
        id: get-release-version
        env:
          commit_msg: ${{needs.collect_commit_message.outputs.commit_msg}}
        run: |
          RELEASE_VERSION="$(echo ${commit_msg} | awk '{for(i=1;i<=NF;i++) if(tolower($i) ~ /release:[0-9]+\.[0-9]+\.[0-9]+/) print tolower($i)}')"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
      - name: Use release version
        env:
          release_version: ${{steps.get-release-version.outputs.RELEASE_VERSION}}
        run: |
          echo "RELEASE is:[${release_version}]"
          
