name: Commit & Store Variables

on: push

jobs:
  collect_commit_message:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - id: get-commit-msg
        name: collect commit message
        run: |
          echo "COMMIT_MESSAGE=$(git show -s --format=%s)" >> "$GITHUB_ENV"
      - name: extract accessible release
        run: |
          RELEASE_COMMIT_PART=$(echo $COMMIT_MESSAGE | awk '{for(i=1;i<=NF;i++) if(tolower($i) ~ /release:[0-9]+\.[0-9]+\.[0-9]+/) print tolower($i)}')
          if [ "${#RELEASE_COMMIT_PART}" -ge 3 ] 
          then
            echo "RELEASE_VERSION=${RELEASE_COMMIT_PART#release:}" >> "$GITHUB_ENV"
          fi
      - name: collect last tag version
        run: |
          LATEST_TAG=$(git tag --sort=-taggerdate | head -1)
          if [ "${#LATEST_TAG}" -ge 3 ]
          then
            echo "TAG_VERSION=$LATEST_TAG" >> "$GITHUB_ENV"
          fi
      - name: trigger workflow build & test
        run: |
          curl -X POST \
                      -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Accept: application/vnd.github.v3+json" \
                      https://api.github.com/repos/mrupgradable/profile-jumper/dispatches \
                      -d '{"event_type":"trigger-build-and-test"}'